### ISSUE TITLE
Add a map of where to get food at the Cambridge kickstart

### ISSUE THREAD

**Issue by Adimote** [srobo/competition-team-minutes#162] opened 2019-10-12 00:16 UTC
From https://github.com/srobo/competition-team-minutes/blob/master/SR2020/2019-10-11.md#specific

**Comment by PeterJCLaw** [comment] 2019-10-12 12:23
This is a duplicate of https://github.com/srobo/competition-team-minutes/issues/156.
@Adimote were you aware that it's possible to link actions to pre-existing issues? (The script detects that and doesn't create duplicates).

**Closed by PeterJCLaw** 2019-10-12 12:23 UTC
