### ISSUE TITLE
Email volunteers with an update and inviting them to get involved

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/competition-team-minutes#277] opened 2021-02-11 21:37 UTC
From https://github.com/srobo/competition-team-minutes/blob/master/SR2021/2021-02-11.md#specific

The email would contain:
- Doings dates

We should check in with the kit team before sending.

**Comment by WillB97** [comment] 2021-03-03 16:17
Is this a duplicate of #285?

**Comment by RealOrangeOne** [comment] 2021-03-03 17:19
Yes and no. This was aimed at a more general "get involved" email, whereas I think #285  was simply notification of a doing. 

Either way neither of the emails have been sent.

We should probably close this in favour of #285, and make sure that email is also a generic "get involved" email.

**Comment by PeterJCLaw** [comment] 2021-03-03 20:28
This was carried forwards into #285.

**Closed** 2021-03-03 20:28 UTC
